version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5775:5775    
    command: 'uvicorn main:app --port=5775 --host=0.0.0.0 --reload'

    volumes:
      - .:/app/
    depends_on:
      - db
  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db      
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: main_service
      volumes: 
        - .db_data:/var/lib/postgresql/data
      ports:
        - 5431:5432
