version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8900:8900
    command: 'python manage.py runserver 0.0.0.0:8900'

    volumes:
      - .:/app/
    depends_on:
      - db

  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python /app/consumer.py'
    depends_on:
      - db

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: admin_service
      volumes: 
        - .db_data:/var/lib/postgresql/data
      ports:
        - 5433:5432
